### PR TITLE
Fixed the "Bug 22872211: [ARM] "Update" template failed after a PR. P…

### PR DESCRIPTION
**Pull request by ptgadmin-cse**
…asses a parameter that doesn't exist"

### CODE REVIEW

**Comment by delradie** [comment]
Just to add, having tested the deployment using the artifacts from this branch the upgrade works successfully now. Thank you so much guys :)

**Comment by ChristianMontoya** [comment]
@delradie : Thanks for the confirmation, and glad it worked for you now!

**Comment by ChristianMontoya** [comment]
Also running a few tests...

**Comment by ChristianMontoya** [comment]
Works for me too. Approving.

**Comment by ptgadmin-cse** [comment]
Thank you Christian.

**Pull request merged**
