### PR TITLE
update bootloader to 1.0.2659.0_27877564

### PR DESCRIPTION
**Pull request by datr93**

### CODE REVIEW

**Comment by lintFan** [comment]
The configuration.zip has a "Configuration" folder in it that needs to be removed for the paths to work.
Also the DSC/DeployAgent.zip file is traditionally also updated with the new MSI files too, this isn't actually used by the template since it uses the DeploAgent.zip inside of Configuration.zip but I think the idea is that updating it in git makes it clearer when the MSIs have changed in a commit.

**Comment by datr93** [comment]
Whoops nice catch. The file pathing is not user friendly with the zipping ui

**Comment by datr93** [comment]
image
image

**Pull request merged**
