### PR TITLE
Igorpag avd patch1

### PR DESCRIPTION
**Pull request by igorpag**
Update the list of rules, two added, one modified.

### CODE REVIEW

**Comment by igorpag** [comment]
#pr-ready

**Comment by igorpag** [comment]
Hi @dhrump can you please merge? thanks.

**Comment by murajput** [comment]
> Hi @dhrump can you please merge? thanks.

Hey, @dhrump has joined a different service. I can help you merging this PR. Could you elaborate the reason for this PR? Thanks

**Comment by igorpag** [comment]
> > Hi @dhrump can you please merge? thanks.
> 
> Hey, @dhrump has joined a different service. I can help you merging this PR. Could you elaborate the reason for this PR? Thanks

I'm the original author of the underlying ARM template to automate the creation of an Azure Firewall Policy to create all the necessary firewall rules to allow Azure Firewall to protect AVD, based on the content from the articles below:

https://learn.microsoft.com/en-us/azure/virtual-desktop/safe-url-list
https://learn.microsoft.com/en-us/azure/firewall/protect-azure-virtual-desktop

Since some rules changed, I submitted this PR to fix the ARM template. 
Thank you.

**Review by murajput — APPROVED** [review]

**Comment by igorpag** [comment]
Thank you for the approval @murajput, can you please also merge? I don't have write access to this repo.
Regards.

**Pull request merged**
