### PR TITLE
Change Domain Join User to UPN

### PR DESCRIPTION
**Pull request by fberson**
The previous configuration assumes that the AD FQDN is always the same as the AD NetBios Name, suggest to change this and pass the Parameter existingDomainUsername since that already contains the full UPN of the user that has permissions to join the VM to the domain

### CODE REVIEW

**Comment by ChristianMontoya** [comment]
@fberson : Looks like we're just getting to this. With our latest version that's in "master", does this edit still bring value?

**Comment by ChristianMontoya** [comment]
@paulomarquesc : Can I get your eyes on this?

**Comment by ChristianMontoya** [comment]
Closing this out as I created a new PR that's easier to test with the latest changes.

**Comment by fberson** [comment]
Hi Christian,

I missed this message earlier, but yes I agree.

FREEK BERSON
06 48378827
www.wortell.nl<http://www.wortell.nl/>
LinkedIn<http://nl.linkedin.com/in/freekberson> | Blog<http://themicrosoftplatform.net/> | Twitter<http://twitter.com/#!/fberson> | MVP<https://mvp.microsoft.com/en-us/PublicProfile/4034966>

**Pull request closed without merging**
