### PR TITLE
Remove public ip parameter from ARM templates

### PR DESCRIPTION
**Pull request by philipktlin**
The best practice for WVD scenario is to NOT use public ip when creating VMs in a host pool.  Therefore we remove public IP parameter from WVD ARM templates.

### CODE REVIEW

**Comment by datr93** [comment]
lgtm make sure you've tested this

**Comment by lintFan** [comment]
@philipktlin what about customers who want to use a public IP though? This removes their ability to do that without customizing having the template, it feels like you might want to talk to PM before making this change since it could break existing customers.

**Comment by lintFan** [comment]
@philipktlin If you are going to make this change after talking to PM it should probably be posted about ahead of time on the [WVD Tech Community ](https://techcommunity.microsoft.com/t5/windows-virtual-desktop/bd-p/WindowsVirtualDesktop), since aside from removing the public IP functionality removing the parameters will break existing deployments of this template.

**Comment by philipktlin** [comment]
> @philipktlin If you are going to make this change after talking to PM it should probably be posted about ahead of time on the [WVD Tech Community ](https://techcommunity.microsoft.com/t5/windows-virtual-desktop/bd-p/WindowsVirtualDesktop), since aside from removing the public IP functionality removing the parameters will break existing deployments of this template.

Thanks for let me know about this.  Normally how long should I commit breaking changes after posted a message to WVD tech community?

**Comment by lintFan** [comment]
It think it was at least two weeks in the past, but PM ultimately decided how long to wait.

**Pull request merged**
